version: '3.8'

services:
  list_ranker-frontend:
    build:
      context: ../../frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://list_ranker-backend:8080
    networks:
      - app-network

  list_ranker-backend:
    build:
      context: ../../backend
      target: development
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SECRET_KEY: "eeeeeeeeee"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - list_ranker-db

  list_ranker-db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
